name: CI
on:
  pull_request:
    branches: [main, dev]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TURBO_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      TURBO_TEAM: ${{ secrets.VERCEL_TEAM_SLUG }}
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
    steps:
      - uses: actions/checkout@master
      - uses: pnpm/action-setup@master
        with:
          version: latest
      - uses: actions/setup-node@master
        with:
          node-version: '16'
          cache: 'pnpm'
      - run: vercel pull --token=${{ secrets.VERCEL_TOKEN }} --yes --environment=preview
      - run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
